### ISSUE TITLE
Can't get project to compile

### ISSUE THREAD

**Issue by alexthelion335** [ethanmancini/SPICE-2#6]
I tried compiling your project, but I can seem to get it to compile. I am running on the AMD64 architecture.

My system:

`
Linux alex-rogzephyrus 6.11.11-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu, 05 Dec 2024 16:26:44 +0000 x86_64 GNU/Linux
`

The errors it gives me:

```
[alex@alex-rogzephyrus SPICE-2]$ ./build 
unix.c:20:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   20 | times_( iarg )
      | ^~~~~~
unix.c: In function ‘times_’:
unix.c:23:9: error: implicit declaration of function ‘times’; did you mean ‘times_’? [-Wimplicit-function-declaration]
   23 |         times( iarg );
      |         ^~~~~
      |         times_
unix.c: At top level:
unix.c:32:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   32 | xtime_( chr )
      | ^~~~~~
unix.c:50:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   50 | xdate_( chr )
      | ^~~~~~
unix.c: In function ‘xdate_’:
unix.c:63:18: warning: unknown escape sequence: '\/'
   63 |         *chr++ = '\/';
      |                  ^~~~
unix.c:67:18: warning: unknown escape sequence: '\/'
   67 |         *chr++ = '\/';
      |                  ^~~~
unix.c: At top level:
unix.c:96:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   96 | dblsgl_( cstar16, numwds )
      | ^~~~~~~
unix.c: In function ‘dblsgl_’:
unix.c:103:9: error: ‘return’ with no value, in function returning non-void [-Wreturn-mismatch]
  103 |         return;
      |         ^~~~~~
unix.c:96:1: note: declared here
   96 | dblsgl_( cstar16, numwds )
      | ^~~~~~~
unix.c: At top level:
unix.c:121:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  121 | iopraw_()
      | ^~~~~~~
unix.c: In function ‘iopraw_’:
unix.c:149:17: error: implicit declaration of function ‘exit’ [-Wimplicit-function-declaration]
  149 |                 exit( 1 );  /* terminate program */
      |                 ^~~~
unix.c:112:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
  111 | #include <stdio.h>
  +++ |+#include <stdlib.h>
  112 | FILE    *rawfile;  /* pointer to raw file  */
unix.c:149:17: warning: incompatible implicit declaration of built-in function ‘exit’ [-Wbuiltin-declaration-mismatch]
  149 |                 exit( 1 );  /* terminate program */
      |                 ^~~~
unix.c:149:17: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
unix.c: At top level:
unix.c:156:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  156 | clsraw_()
      | ^~~~~~~
unix.c:164:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  164 | fwrite_( data, numwds )
      | ^~~~~~~
unix.c:176:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  176 | move_( array1, index1, array2, index2, length )
      | ^~~~~
unix.c: In function ‘move_’:
unix.c:183:9: error: implicit declaration of function ‘mcopy’ [-Wimplicit-function-declaration]
  183 |         mcopy( array2, array1, *length );
      |         ^~~~~
unix.c: At top level:
unix.c:202:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  202 | zero4_( array, length )
      | ^~~~~~
unix.c: In function ‘zero4_’:
unix.c:206:9: error: implicit declaration of function ‘mclear’ [-Wimplicit-function-declaration]
  206 |         mclear( array, *length * 8 );
      |         ^~~~~~
unix.c: At top level:
unix.c:210:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  210 | zero8_( array, length )
      | ^~~~~~
unix.c:218:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  218 | zero16_( array, length )
      | ^~~~~~~
unix.c:226:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  226 | copy4_( from, to, length )
      | ^~~~~~
unix.c:234:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  234 | copy8_( from, to, length )
      | ^~~~~~
unix.c:242:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  242 | copy16_( from, to, length )
      | ^~~~~~~
unix.c:262:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  262 | mclear( data, size )
      | ^~~~~~
unix.c:286:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  286 | mcopy( from, to, size )
      | ^~~~~
[alex@alex-rogzephyrus SPICE-2]$

```

**Comment by tvrusso** [comment]
FWIW, the "build" script was removed and replaced with a makefile in commit 2532505, which for some reason only happend on the "mac-os" branch and was never merged to master, but contains all the changes on master as well as a few that were associated with fixing the build for mac os.

Switch to the mac-os branch and use "make" instead of "./build"

The errors you're seeing were always showing up as warnings before, but you must be using a newer version of gcc where those warnings have turned into errors instead, or somewhere in your version of the clone the "-Werror" option is being set.   Try adding "-Wno-error" to the makefile's CXXFLAGS to return these "errors" to the warnings they were when the code was posted.

These aren't really errors:  the functions flagged have no return value and no return value is used, but they were not declared as void, so the compiler warns about them.  That it is now treating that warning as errors is annoying, but telling it not to hurts nothing in this case.

**Comment by ethanmancini** [comment]
The merge was accepted; errors should be fixed on the master branch now.

**Comment by alexthelion335** [comment]
I cloned the new commit with the makefile and I still get the same errors. I checked the makefile and it has the -Wno-error option set in CFLAGS. Just to test I made a new variable CXXFLAGS in the makefile and that didn't fix it either.

**Comment by alexthelion335** [comment]
I worked with one of my programmer friends and he said to try -fpermissive instead of -Wno-error in the makefile, that seemed to make it compile.

I think I did the benchmark correctly (I abbreviated the output):

```
1*******02/09/25 ********  SPICE 2G.6    3/15/83 ********03:20:45*****

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          

0****     INPUT LISTING                    TEMPERATURE =   27.000 DEG C

0***********************************************************************



 .WIDTH IN=72    
 .OPT ACCT LIST NODE LVLCOD=2    
 .TF V(5) VIN    
 .DC VIN -0.25 0.25 0.005
 .AC DEC 10 1 10GHZ      
 .TRAN 5NS 500NS 
 VIN 1 0 SIN(0 0.1 5MEG) AC 1    
 VCC 8 0 12      
 VEE 9 0 -12     
 Q1 4 2 6 QNL    
 Q2 5 3 6 QNL    
 RS1 1 2 1K      
 RS2 3 0 1K      
 RC1 4 8 10K     
 RC2 5 8 10K     
 Q3 6 7 9 QNL    
 Q4 7 7 9 QNL    
 RBIAS 7 8 20K   
 .MODEL QNL NPN(BF=80 RB=100 CCS=2PF TF=0.3NS TR=6NS CJE=3PF CJC=2PF     
 +   VA=50)      
 .PRINT DC V(4) V(5)     
 .PLOT DC V(5)   
 .PRINT AC VM(5) VP(5)   
 .PLOT AC VM(5) VP(5)    
 .PRINT TRAN V(4) V(5)   
 .PLOT TRAN V(5) 
 .END    
1****************02/09/25 ************************  SPICE 2G.6    3/15/83 ************************03:20:45****************

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          
0****                 CIRCUIT ELEMENT SUMMARY                              TEMPERATURE =   27.000 DEG C

0*************************************************************************************************************************




0**** RESISTORS
0     NAME        NODES     VALUE       TC1        TC2


      RS1         1    2   1.00D+03   0.00D+00   0.00D+00
      RS2         3    0   1.00D+03   0.00D+00   0.00D+00
      RC1         4    8   1.00D+04   0.00D+00   0.00D+00
      RC2         5    8   1.00D+04   0.00D+00   0.00D+00
      RBIAS       7    8   2.00D+04   0.00D+00   0.00D+00


0**** INDEPENDENT SOURCES
0     NAME        NODES   DC VALUE   AC VALUE   AC PHASE   TRANSIENT


      VIN         1    0   0.00D+00   1.00D+00   0.00D+00  SIN     
0                                          OFFSET.......   0.00D+00
                                           AMPLITUDE....   1.00D-01
                                           FREQUENCY....   5.00D+06
                                           DELAY........   0.00D+00
                                           THETA........   0.00D+00

      VCC         8    0   1.20D+01   0.00D+00   0.00D+00          
      VEE         9    0  -1.20D+01   0.00D+00   0.00D+00          


0**** BIPOLAR JUNCTION TRANSISTORS
0     NAME        C    B    E    S  MODEL       AREA


      Q1          4    2    6    0  QNL        1.000          
      Q2          5    3    6    0  QNL        1.000          
      Q3          6    7    9    0  QNL        1.000          
      Q4          7    7    9    0  QNL        1.000          
1****************02/09/25 ************************  SPICE 2G.6    3/15/83 ************************03:20:45****************

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          
0****                 ELEMENT NODE TABLE                                   TEMPERATURE =   27.000 DEG C

0*************************************************************************************************************************


0      0    RS2      VIN      VCC      VEE      Q1       Q2       Q3       Q4      
0      1    RS1      VIN     
0      2    RS1      Q1      
0      3    RS2      Q2      
0      4    RC1      Q1      
0      5    RC2      Q2      
0      6    Q1       Q2       Q3      
0      7    RBIAS    Q3       Q4       Q4      
0      8    RC1      RC2      RBIAS    VCC     
0      9    VEE      Q3       Q4      
1****************02/09/25 ************************  SPICE 2G.6    3/15/83 ************************03:20:45****************

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          
0****                 BJT MODEL PARAMETERS                                 TEMPERATURE =   27.000 DEG C

0*************************************************************************************************************************




             QNL     
0TYPE        NPN   
0IS        1.00D-16
0BF          80.000
0NF           1.000
0VAF       5.00D+01
0BR           1.000
0NR           1.000
0RB         100.000
0CJE       3.00D-12
0TF        3.00D-10
0CJC       2.00D-12
0TR        6.00D-09
0CJS       2.00D-12
1****************02/09/25 ************************  SPICE 2G.6    3/15/83 ************************03:20:45****************

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          
0****                 DC TRANSFER CURVES                                   TEMPERATURE =   27.000 DEG C

0*************************************************************************************************************************



   VIN          V(4)        V(5)        
X
 
 -2.500E-01     1.196E+01  -7.957E-01
 -2.450E-01     1.195E+01  -7.948E-01
 -2.400E-01     1.195E+01  -7.938E-01
 -2.350E-01     1.194E+01  -7.926E-01
 -2.300E-01     1.193E+01  -7.912E-01
 -2.250E-01     1.191E+01  -7.897E-01
 -2.200E-01     1.190E+01  -7.880E-01
 -2.150E-01     1.189E+01  -7.860E-01
 -2.100E-01     1.187E+01  -7.839E-01
 -2.050E-01     1.185E+01  -7.816E-01
 -2.000E-01     1.183E+01  -7.791E-01
 -1.950E-01     1.181E+01  -7.764E-01
 -1.900E-01     1.179E+01  -7.735E-01
 -1.850E-01     1.177E+01  -7.703E-01
 -1.800E-01     1.174E+01  -7.669E-01
 -1.750E-01     1.172E+01  -7.634E-01
 -1.700E-01     1.169E+01  -7.596E-01
 -1.650E-01     1.166E+01  -7.555E-01
 -1.600E-01     1.163E+01  -7.513E-01
 -1.550E-01     1.160E+01  -7.468E-01
 -1.500E-01     1.157E+01  -7.420E-01
 -1.450E-01     1.154E+01  -7.369E-01
 -1.400E-01     1.151E+01  -7.316E-01
 -1.350E-01     1.147E+01  -7.258E-01
 -1.300E-01     1.144E+01  -7.197E-01
 -1.250E-01     1.140E+01  -7.130E-01
 -1.200E-01     1.136E+01  -7.058E-01
 -1.150E-01     1.133E+01  -6.976E-01
 -1.100E-01     1.129E+01  -6.883E-01
 -1.050E-01     1.124E+01  -6.772E-01
 -1.000E-01     1.120E+01  -6.627E-01
 -9.500E-02     1.115E+01  -6.407E-01
 -9.000E-02     1.108E+01  -5.907E-01
 -8.500E-02     1.093E+01  -4.536E-01
 -8.000E-02     1.076E+01  -2.784E-01
 -7.500E-02     1.056E+01  -8.128E-02
 -7.000E-02     1.034E+01   1.382E-01
 -6.500E-02     1.009E+01   3.807E-01
 -6.000E-02     9.827E+00   6.462E-01
 -5.500E-02     9.537E+00   9.346E-01
 -5.000E-02     9.225E+00   1.245E+00
 -4.500E-02     8.891E+00   1.577E+00
 -4.000E-02     8.538E+00   1.929E+00
 -3.500E-02     8.167E+00   2.299E+00
 -3.000E-02     7.779E+00   2.685E+00
 -2.500E-02     7.376E+00   3.086E+00
 -2.000E-02     6.962E+00   3.500E+00
 -1.500E-02     6.537E+00   3.923E+00
 -1.000E-02     6.105E+00   4.354E+00
 -5.000E-03     5.669E+00   4.790E+00
 -5.551E-17     5.229E+00   5.229E+00
  5.000E-03     4.790E+00   5.668E+00
  1.000E-02     4.353E+00   6.104E+00
  1.500E-02     3.921E+00   6.536E+00
  2.000E-02     3.497E+00   6.960E+00
  2.500E-02     3.083E+00   7.374E+00
  3.000E-02     2.682E+00   7.776E+00
  3.500E-02     2.294E+00   8.163E+00
  4.000E-02     1.924E+00   8.535E+00
  4.500E-02     1.571E+00   8.887E+00
  5.000E-02     1.238E+00   9.221E+00
  5.500E-02     9.268E-01   9.532E+00
  6.000E-02     6.375E-01   9.822E+00
  6.500E-02     3.708E-01   1.009E+01
  7.000E-02     1.272E-01   1.033E+01
  7.500E-02    -9.349E-02   1.055E+01
  8.000E-02    -2.918E-01   1.075E+01
  8.500E-02    -4.644E-01   1.093E+01
  9.000E-02    -5.416E-01   1.102E+01
  9.500E-02    -5.641E-01   1.107E+01
  1.000E-01    -5.757E-01   1.112E+01
  1.050E-01    -5.829E-01   1.116E+01
  1.100E-01    -5.881E-01   1.119E+01
  1.150E-01    -5.920E-01   1.123E+01
  1.200E-01    -5.949E-01   1.126E+01
  1.250E-01    -5.972E-01   1.130E+01
  1.300E-01    -5.989E-01   1.133E+01
  1.350E-01    -6.003E-01   1.136E+01
  1.400E-01    -6.013E-01   1.140E+01
  1.450E-01    -6.020E-01   1.143E+01
  1.500E-01    -6.025E-01   1.146E+01
  1.550E-01    -6.027E-01   1.149E+01
  1.600E-01    -6.027E-01   1.152E+01
  1.650E-01    -6.026E-01   1.155E+01
  1.700E-01    -6.023E-01   1.158E+01
  1.750E-01    -6.018E-01   1.160E+01
  1.800E-01    -6.011E-01   1.163E+01
  1.850E-01    -6.003E-01   1.165E+01
  1.900E-01    -5.994E-01   1.168E+01
  1.950E-01    -5.982E-01   1.170E+01
  2.000E-01    -5.970E-01   1.173E+01
  2.050E-01    -5.956E-01   1.175E+01
  2.100E-01    -5.940E-01   1.177E+01
  2.150E-01    -5.923E-01   1.179E+01
  2.200E-01    -5.904E-01   1.181E+01
  2.250E-01    -5.884E-01   1.183E+01
  2.300E-01    -5.863E-01   1.185E+01
  2.350E-01    -5.840E-01   1.186E+01
  2.400E-01    -5.815E-01   1.188E+01
  2.450E-01    -5.789E-01   1.189E+01
  2.500E-01    -5.762E-01   1.190E+01
Y
1****************02/09/25 ************************  SPICE 2G.6    3/15/83 ************************03:20:45****************

0DIFPAIR CKT - SIMPLE DIFFERENTIAL PAIR                                          
0****                 DC TRANSFER CURVES                                   TEMPERATURE =   27.000 DEG C

0*************************************************************************************************************************


X
   VIN         V(5)    

                      -5.000D+00                0.000D+00                5.000D+00                1.000D+01                1.500D+01
                           - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-2.500D-01   -7.957D-01   .                    *   .                        .                        .                        .   
-2.450D-01   -7.948D-01   .                    *   .                        .                        .                        .   
-2.400D-01   -7.938D-01   .                    *   .                        .                        .                        .   
-2.350D-01   -7.926D-01   .                    *   .                        .                        .                        .   
-2.300D-01   -7.912D-01   .                    *   .                        .                        .                        .   
-2.250D-01   -7.897D-01   .                    *   .                        .                        .                        .   
-2.200D-01   -7.880D-01   .                    *   .                        .                        .                        .   
-2.150D-01   -7.860D-01   .                    *   .                        .                        .                        .   
-2.100D-01   -7.839D-01   .                    *   .                        .                        .                        .   
-2.050D-01   -7.816D-01   .                    *   .                        .                        .                        .   
-2.000D-01   -7.791D-01   .                    *   .                        .                        .                        .   
-1.950D-01   -7.764D-01   .                    *   .                        .                        .                        .   
-1.900D-01   -7.735D-01   .                    *   .                        .                        .                        .   
-1.850D-01   -7.703D-01   .                    *   .                        .                        .                        .   
-1.800D-01   -7.669D-01   .                    *   .                        .                        .                        .   
-1.750D-01   -7.634D-01   .                    *   .                        .                        .                        .   
-1.700D-01   -7.596D-01   .                    *   .                        .                        .                        .   
-1.650D-01   -7.555D-01   .                    *   .                        .                        .                        .   
-1.600D-01   -7.513D-01   .                    *   .                        .                        .                        .   
-1.550D-01   -7.468D-01   .                    *   .                        .                        .                        .   
-1.500D-01   -7.420D-01   .                    *   .                        .                        .                        .   
-1.450D-01   -7.369D-01   .                    *   .                        .                        .                        .   
-1.400D-01   -7.316D-01   .                    *   .                        .                        .                        .   
-1.350D-01   -7.258D-01   .                    *   .                        .                        .                        .   
-1.300D-01   -7.197D-01   .                    *   .                        .                        .                        .   
-1.250D-01   -7.130D-01   .                    *   .                        .                        .                        .   
-1.200D-01   -7.058D-01   .                    *   .                        .                        .                        .   
-1.150D-01   -6.976D-01   .                     *  .                        .                        .                        .   
-1.100D-01   -6.883D-01   .                     *  .                        .                        .                        .   
-1.050D-01   -6.772D-01   .                     *  .                        .                        .                        .   
-1.000D-01   -6.627D-01   .                     *  .                        .                        .                        .   
-9.500D-02   -6.407D-01   .                     *  .                        .                        .                        .   
-9.000D-02   -5.907D-01   .                     *  .                        .                        .                        .   
-8.500D-02   -4.536D-01   .                      * .                        .                        .                        .   
-8.000D-02   -2.784D-01   .                       *.                        .                        .                        .   
-7.500D-02   -8.128D-02   .                        *                        .                        .                        .   
-7.000D-02    1.382D-01   .                        .*                       .                        .                        .   
-6.500D-02    3.807D-01   .                        . *                      .                        .                        .   
-6.000D-02    6.462D-01   .                        .  *                     .                        .                        .   
-5.500D-02    9.346D-01   .                        .    *                   .                        .                        .   
-5.000D-02    1.245D+00   .                        .     *                  .                        .                        .   
-4.500D-02    1.577D+00   .                        .       *                .                        .                        .   
-4.000D-02    1.929D+00   .                        .         *              .                        .                        .   
-3.500D-02    2.299D+00   .                        .          *             .                        .                        .   
-3.000D-02    2.685D+00   .                        .            *           .                        .                        .   
-2.500D-02    3.086D+00   .                        .              *         .                        .                        .   
-2.000D-02    3.500D+00   .                        .                *       .                        .                        .   
-1.500D-02    3.923D+00   .                        .                   *    .                        .                        .   
-1.000D-02    4.354D+00   .                        .                     *  .                        .                        .   
-5.000D-03    4.790D+00   .                        .                       *.                        .                        .   
-5.551D-17    5.229D+00   .                        .                        .*                       .                        .   
 5.000D-03    5.668D+00   .                        .                        .  *                     .                        .   
 1.000D-02    6.104D+00   .                        .                        .     *                  .                        .   
 1.500D-02    6.536D+00   .                        .                        .       *                .                        .   
 2.000D-02    6.960D+00   .                        .                        .         *              .                        .   
 2.500D-02    7.374D+00   .                        .                        .           *            .                        .   
 3.000D-02    7.776D+00   .                        .                        .             *          .                        .   
 3.500D-02    8.163D+00   .                        .                        .               *        .                        .   
 4.000D-02    8.535D+00   .                        .                        .                 *      .                        .   
 4.500D-02    8.887D+00   .                        .                        .                  *     .                        .   
 5.000D-02    9.221D+00   .                        .                        .                    *   .                        .   
 5.500D-02    9.532D+00   .                        .                        .                      * .                        .   
 6.000D-02    9.822D+00   .                        .                        .                       *.                        .   
 6.500D-02    1.009D+01   .                        .                        .                        *                        .   
 7.000D-02    1.033D+01   .                        .                        .                        . *                      .   
 7.500D-02    1.055D+01   .                        .                        .                        .  *                     .   
 8.000D-02    1.075D+01   .                        .                        .                        .   *                    .   
 8.500D-02    1.093D+01   .                        .                        .                        .    *                   .   
 9.000D-02    1.102D+01   .                        .                        .                        .    *                   .   
 9.500D-02    1.107D+01   .                        .                        .                        .    *                   .   
 1.000D-01    1.112D+01   .                        .                        .                        .     *                  .   
 1.050D-01    1.116D+01   .                        .                        .                        .     *                  .   
 1.100D-01    1.119D+01   .                        .                        .                        .     *                  .   
 1.150D-01    1.123D+01   .                        .                        .                        .     *                  .   
 1.200D-01    1.126D+01   .                        .                        .                        .     *                  .   
 1.250D-01    1.130D+01   .                        .                        .                        .     *                  .   
 1.300D-01    1.133D+01   .                        .                        .                        .      *                 .   
 1.350D-01    1.136D+01   .                        .                        .                        .      *                 .   
 1.400D-01    1.140D+01   .                        .                        .                        .      *                 .   
 1.450D-01    1.143D+01   .                        .                        .                        .      *                 .   
 1.500D-01    1.146D+01   .                        .                        .                        .      *                 .   
 1.550D-01    1.149D+01   .                        .                        .                        .      *                 .   
 1.600D-01    1.152D+01   .                        .                        .                        .       *                .   
 1.650D-01    1.155D+01   .                        .                        .                        .       *                .   
 1.700D-01    1.158D+01   .                        .                        .                        .       *                .   
 1.750D-01    1.160D+01   .                        .                        .                        .       *                .   
 1.800D-01    1.163D+01   .                        .                        .                        .       *                .   
 1.850D-01    1.165D+01   .                        .                        .                        .       *                .   
 1.900D-01    1.168D+01   .                        .                        .                        .       *                .   
 1.950D-01    1.170D+01   .                        .                        .                        .        *               .   
 2.000D-01    1.173D+01   .                        .                        .                        .        *               .   
 2.050D-01    1.175D+01   .                        .                        .                        .        *               .   
 2.100D-01    1.177D+01   .                        .                        .                        .        *               .   
 2.150D-01    1.179D+01   .                        .                        .                        .        *               .   
 2.200D-01    1.181D+01   .                        .                        .                        .        *               .   
 2.250D-01    1.183D+01   .                        .                        .                        .        *               .   
 2.300D-01    1.185D+01   .                        .                        .                        .        *               .   
 2.350D-01    1.186D+01   .                        .                        .                        .        *               .   
 2.400D-01    1.188D+01   .                        .                        .                        .        *               .   
 2.450D-01    1.189D+01   .                        .                        .                        .        *               .   
 2.500D-01    1.190D+01   .                        .                        .                        .         *              .   
                           - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

...

```

**Comment by tvrusso** [comment]
Yes, -fpermissive is probably the better option.

I have compiled spice-2 with GCC as recent as GCC 13 and neither "-fpermissive" nor "-Wno-error" was needed, so clearly some later version of GCC has gotten less forgiving of warnings than it used to be.  In fact, I have no access to a version of GCC that errored out on this code, so my "-Wno-error" was a guess because the behavior you're seeing is exactly what you would get if you gave "-Werror" to older versions of GCC.

I hit a hiccup trying to fix the actual errors and it took longer than I expected, but I will try to get back to that.  That would be the definitive solution of the problem.  But working around GCC's sudden decision to turn some warnings into errors is the stopgap.

**Comment by tvrusso** [comment]
A safer alternative to "-fpermissive" (which turns all warnings like this into errors) would be to disable just the one warning that is causing problems here.   That could be done with "-Wno-error=implicit-int", or at least it could be done in the older versions of GCC to which I have access.

Could you try that out instead of "-fpermissive" and let me know if it fixes the problem or not?  If so, I'll make another PR updating the makefile one way or another.

**Comment by alexthelion335** [comment]
There was another error as well not allowing it to compile, implicit-function-declaration. I updated the makefile with those two -Wno-error statements and it works now.

This is what the makefile looks like now:

```
CC = gcc
CFLAGS = -g -O0 -Wno-error=implicit-int -Wno-error=implicit-function-declaration
FC = gfortran
FFLAGS = -g -O0 -finteger-4-integer-8 -std=legacy

OBJS = spice.o unix.o

all: spice

spice: $(OBJS)
        $(FC) $(OBJS) -o spice

%.o: %.f
        $(FC) -c $(FFLAGS) $*.f -o $*.o 

%.o: %.c
        $(CC) $(CFLAGS) -c $*.c -o $*.o

clean:
        rm -f $(OBJS) spice


```

**Comment by tvrusso** [comment]
I think using those two options is the best solution for now.

Fixing the code is worthwhile, but it's important to remember that this is ancient, obsolete software that is of at most novelty interest --- SPICE2 was made obsolete back in the early 1980s when SPICE3 was written in C, and SPICE3 is the one on which almost all commercial SPICE simulators are based.  SPICE3 has its own problems, but those are all being addressed by ng-spice, which is under active development.

Very recent versions of GCC seem to be enforcing modern coding standards, whereas when this code was written it was explicitly taking advantage of what was then just default behavior of C compilers.

Telling newer compilers not to enforce their coding standards on ancient code is not an unreasonable thing, and those two options do just that.
